# Use an official Node.js runtime to build the app
FROM node:20-alpine as build

# Set the working directory inside the container
WORKDIR /frontend-app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the React code to the container
COPY . .

# Build the React app for production
RUN npm run build

# Use a lightweight web server to serve the build files
FROM node:20-alpine
WORKDIR /frontend-app
COPY --from=build /frontend-app/build ./build
RUN npm install -g serve
CMD ["serve", "-s", "build"]
EXPOSE 3000
