# Official Node.js runtime base image
FROM node:20-alpine as build

# Setting the working directory inside the container
WORKDIR /backend-app

# Copying package.json and package-lock.json to the working directory
COPY package*.json ./

# Installing dependencies
RUN npm install --production

# Copying the rest of the backend code to the container
COPY . .

# Exposing the port the app runs on
EXPOSE 5010

# Command to start the backend server
CMD ["npm", "start"]
