# Use an official Node.js runtime as the base image
FROM node:20-alpine as build

# Set the working directory inside the container
WORKDIR /backend-app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the backend code to the container
COPY . .

# Expose the port your app runs on (e.g., 5000)
EXPOSE 5010

# Command to start the backend server
CMD ["npm", "start"]
